#include <Warsaw/Allocation.idl>
#include <Warsaw/Figure.idl>
#include <Warsaw/Observer.idl>
#include <Warsaw/TextBuffer.idl>
#include <Warsaw/BoundedRange.idl>
#include <Warsaw/FigureKit.idl>
#include <Warsaw/PickTraversal.idl>
#include <Warsaw/TextKit.idl>
#include <Warsaw/BoundedValue.idl>
#include <Warsaw/Focus.idl>
#include <Warsaw/Primitive.idl>
#include <Warsaw/ToolKit.idl>
#include <Warsaw/Canvas.idl>
#include <Warsaw/GadgetKit.idl>
#include <Warsaw/PrimitiveKit.idl>
#include <Warsaw/Transform.idl>
#include <Warsaw/ClientContext.idl>
#include <Warsaw/GGIKit.idl>
#include <Warsaw/Raster.idl>
#include <Warsaw/Traversal.idl>
#include <Warsaw/Command.idl>
#include <Warsaw/Graphic.idl>
#include <Warsaw/RefCountBase.idl>
#include <Warsaw/Trigger.idl>
#include <Warsaw/CommandKit.idl>
#include <Warsaw/Grid.idl>
#include <Warsaw/Region.idl>
#include <Warsaw/Types.idl>
#include <Warsaw/Controller.idl>
#include <Warsaw/Identifiable.idl>
#include <Warsaw/Screen.idl>
#include <Warsaw/UnidrawKit.idl>
#include <Warsaw/Image.idl>
#include <Warsaw/Selection.idl>
#include <Warsaw/View.idl>
#include <Warsaw/Desktop.idl>
#include <Warsaw/ImageKit.idl>
#include <Warsaw/Server.idl>
#include <Warsaw/Viewport.idl>
#include <Warsaw/DesktopKit.idl>
#include <Warsaw/Input.idl>
#include <Warsaw/Stage.idl>
#include <Warsaw/Drawable.idl>
#include <Warsaw/Kit.idl>
#include <Warsaw/State.idl>
#include <Warsaw/Widget.idl>
#include <Warsaw/DrawingKit3D.idl>
#include <Warsaw/LayoutKit.idl>
#include <Warsaw/StreamBuffer.idl>
#include <Warsaw/WidgetKit.idl>
#include <Warsaw/DrawingKit.idl>
#include <Warsaw/MainController.idl>
#include <Warsaw/Subject.idl>
#include <Warsaw/Window.idl>
#include <Warsaw/DrawTraversal.idl>
#include <Warsaw/MenuKit.idl>
#include <Warsaw/Telltale.idl>
