#include <Fresco/Allocation.idl>
#include <Fresco/Figure.idl>
#include <Fresco/Observer.idl>
#include <Fresco/TextBuffer.idl>
#include <Fresco/BoundedRange.idl>
#include <Fresco/FigureKit.idl>
#include <Fresco/PickTraversal.idl>
#include <Fresco/TextKit.idl>
#include <Fresco/BoundedValue.idl>
#include <Fresco/Focus.idl>
#include <Fresco/Primitive.idl>
#include <Fresco/ToolKit.idl>
#include <Fresco/Canvas.idl>
#include <Fresco/GadgetKit.idl>
#include <Fresco/PrimitiveKit.idl>
#include <Fresco/Transform.idl>
#include <Fresco/ClientContext.idl>
#include <Fresco/GGIKit.idl>
#include <Fresco/Raster.idl>
#include <Fresco/Traversal.idl>
#include <Fresco/Command.idl>
#include <Fresco/Graphic.idl>
#include <Fresco/RefCountBase.idl>
#include <Fresco/Trigger.idl>
#include <Fresco/CommandKit.idl>
#include <Fresco/Grid.idl>
#include <Fresco/Region.idl>
#include <Fresco/Types.idl>
#include <Fresco/Controller.idl>
#include <Fresco/Identifiable.idl>
#include <Fresco/Screen.idl>
#include <Fresco/UnidrawKit.idl>
#include <Fresco/Image.idl>
#include <Fresco/Selection.idl>
#include <Fresco/View.idl>
#include <Fresco/Desktop.idl>
#include <Fresco/ImageKit.idl>
#include <Fresco/Server.idl>
#include <Fresco/Viewport.idl>
#include <Fresco/DesktopKit.idl>
#include <Fresco/Input.idl>
#include <Fresco/Stage.idl>
#include <Fresco/Drawable.idl>
#include <Fresco/Kit.idl>
#include <Fresco/State.idl>
#include <Fresco/Widget.idl>
#include <Fresco/DrawingKit3D.idl>
#include <Fresco/LayoutKit.idl>
#include <Fresco/StreamBuffer.idl>
#include <Fresco/WidgetKit.idl>
#include <Fresco/DrawingKit.idl>
#include <Fresco/MainController.idl>
#include <Fresco/Subject.idl>
#include <Fresco/Window.idl>
#include <Fresco/DrawTraversal.idl>
#include <Fresco/MenuKit.idl>
#include <Fresco/Telltale.idl>
